#pragma once

/**
 * \file autons.hpp
 *
 * Autonomous routine declarations.
 *
 * Three files work together to set up autonomous:
 *   - autons.hpp        — declare every auton function (this file)
 *   - autons.cpp        — write the actual autonomous code
 *   - auton_config.cpp  — register each auton with the brain-screen picker
 *
 * Workflow for adding a new routine:
 *   1. Declare it here:   `void my_auton();`
 *   2. Write it in autons.cpp
 *   3. Register it in auton_config.cpp:
 *      `light::auton_selector.add("Label", "na", my_auton);`
 */

/**
 * \name Setup functions
 * Called once by `initialize()` in main. Do not rename these.
 * @{
 */
void default_constants();  ///< Tune PID gains, exit conditions, and slew rates.
void default_positions();  ///< Set starting piston / mechanism states.
/** @} */

/**
 * \name Autonomous routines
 * Competition autonomous entry points.
 * @{
 */
/** Run the path generated by the JerryIO path planner (path 1). */
void run_jerryio_path_1();
/** @} */

/**
 * \name Test / tuning routines
 * Useful during practice for dialing in PID. Register these in
 * auton_config.cpp during tuning sessions; remove them before competition.
 * @{
 */
void con_test();                 ///< Basic connectivity / control check.
void drive_test(int inches);     ///< Drive straight N inches — tune drive PID.
void turn_test(int degrees);     ///< Turn to N degrees — tune turn PID.
void swing_test(int degrees);    ///< Swing to N degrees — tune swing PID.
void heading_test(int degrees);  ///< Drive while fighting a heading offset.
void odom_test(int degrees);     ///< Zero odom then drive 24 in — test odometry.
/** @} */
