"""
C++ emitter for sliced field maps.

Produces a self-contained `<face>_map.cpp` that matches the contract in
include/Lightlib/drive/field_map.hpp: each per-face raycast() delegates to
the perimeter raycast() (slab math, already in the library) and then walks
the segment array for interior geometry.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class Segment:
    x1: float
    y1: float
    x2: float
    y2: float


_TEMPLATE = """\
// src/maps/{face}_map.cpp
// AUTO-GENERATED by tools/map_gen/slice.py - DO NOT EDIT BY HAND.
//
// Source CAD       : {cad}
// Sensor height    : {height:.3f} in
// Segments emitted : {n_segments}
// Regenerate       : python tools/map_gen/slice.py --face {face} --height {height} --cad {cad}

#include "Lightlib/drive/field_map.hpp"

#include <algorithm>
#include <cmath>

namespace light::field {{
namespace {{

constexpr float SENSOR_HEIGHT_IN = {height:.3f}f;

struct Seg {{ float x1, y1, x2, y2; }};

constexpr Seg kSegments[] = {{
{segments_block}}};

constexpr int kNumSegments = static_cast<int>(sizeof(kSegments) / sizeof(Seg));

// 2D ray vs line segment. ox/oy is the ray origin; dx/dy is the ray
// direction (need not be unit length, but slice.py emits world-frame rays
// where (dx,dy) = (sin theta, cos theta) so it is). Returns positive t
// along the ray to the hit, or kNoHit if the ray misses the segment.
constexpr float kNoHit = 1.0e30f;
inline float ray_vs_seg(float ox, float oy, float dx, float dy, const Seg& s) {{
  const float ex = s.x2 - s.x1;
  const float ey = s.y2 - s.y1;
  const float denom = dx * ey - dy * ex;
  if (std::fabs(denom) < 1e-6f) return kNoHit;     // parallel or zero-length
  const float rx = s.x1 - ox;
  const float ry = s.y1 - oy;
  const float t = (rx * ey - ry * ex) / denom;     // along ray
  const float u = (rx * dy - ry * dx) / denom;     // along segment
  if (t <= 0.0f || u < 0.0f || u > 1.0f) return kNoHit;
  return t;
}}

}}  // namespace

float raycast_{face}(float x, float y, float angleRad, float max_range) {{
  // Perimeter via the library's slab routine (handles starting-near-wall
  // robustness and the "outside the field returns 0" contract).
  float t = raycast(x, y, angleRad, max_range);

  const float dx = std::sin(angleRad);
  const float dy = std::cos(angleRad);
  for (int i = 0; i < kNumSegments; ++i) {{
    const float ti = ray_vs_seg(x, y, dx, dy, kSegments[i]);
    if (ti > 0.0f && ti < t) t = ti;
  }}
  return std::min(t, max_range);
}}

}}  // namespace light::field
"""


def _format_segments_block(segments: Iterable[Segment]) -> str:
    rows = [
        f"    {{ {s.x1:9.3f}f, {s.y1:9.3f}f, {s.x2:9.3f}f, {s.y2:9.3f}f }},"
        for s in segments
    ]
    if not rows:
        return "    // (no interior segments at this height; perimeter only)\n"
    return "\n".join(rows) + "\n"


def emit_face_map(
    face: str,
    height_in: float,
    cad_path: str,
    segments: list[Segment],
) -> str:
    """Render the C++ source for a single face's map file."""
    if face not in ("front", "back", "left", "right"):
        raise ValueError(f"face must be front/back/left/right, got {face!r}")
    return _TEMPLATE.format(
        face=face,
        height=height_in,
        cad=cad_path,
        n_segments=len(segments),
        segments_block=_format_segments_block(segments),
    )


def write_face_map(
    out_path: Path,
    face: str,
    height_in: float,
    cad_path: str,
    segments: list[Segment],
) -> None:
    """Write the rendered C++ source to disk."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        emit_face_map(face, height_in, cad_path, segments),
        encoding="utf-8",
        newline="\n",
    )
