// src/maps/front_map.cpp
// AUTO-GENERATED by tools/map_gen/slice.py - DO NOT EDIT BY HAND.
//
// Source CAD       : tools/map_gen/cad/OverrideField.STEP
// Sensor height    : 2.500 in
// Segments emitted : 0
// Regenerate       : python tools/map_gen/slice.py --face front --height 2.5 --cad tools/map_gen/cad/OverrideField.STEP

#include "LightLib/path/field_map.hpp"

#include <algorithm>
#include <cmath>

namespace light::field {
namespace {

constexpr float SENSOR_HEIGHT_IN = 2.500f;

struct Seg { float x1, y1, x2, y2; };

constexpr Seg kSegments[] = {
    // (no interior segments at this height; perimeter only)
};

constexpr int kNumSegments = static_cast<int>(sizeof(kSegments) / sizeof(Seg));

// 2D ray vs line segment. ox/oy is the ray origin; dx/dy is the ray
// direction (need not be unit length, but slice.py emits world-frame rays
// where (dx,dy) = (sin theta, cos theta) so it is). Returns positive t
// along the ray to the hit, or kNoHit if the ray misses the segment.
constexpr float kNoHit = 1.0e30f;
inline float ray_vs_seg(float ox, float oy, float dx, float dy, const Seg& s) {
  const float ex = s.x2 - s.x1;
  const float ey = s.y2 - s.y1;
  const float denom = dx * ey - dy * ex;
  if (std::fabs(denom) < 1e-6f) return kNoHit;     // parallel or zero-length
  const float rx = s.x1 - ox;
  const float ry = s.y1 - oy;
  const float t = (rx * ey - ry * ex) / denom;     // along ray
  const float u = (rx * dy - ry * dx) / denom;     // along segment
  if (t <= 0.0f || u < 0.0f || u > 1.0f) return kNoHit;
  return t;
}

}  // namespace

float raycast_front(float x, float y, float angleRad, float max_range) {
  // Perimeter via the library's slab routine (handles starting-near-wall
  // robustness and the "outside the field returns 0" contract).
  float t = raycast(x, y, angleRad, max_range);

  const float dx = std::sin(angleRad);
  const float dy = std::cos(angleRad);
  for (int i = 0; i < kNumSegments; ++i) {
    const float ti = ray_vs_seg(x, y, dx, dy, kSegments[i]);
    if (ti > 0.0f && ti < t) t = ti;
  }
  return std::min(t, max_range);
}

}  // namespace light::field
